### ISSUE TITLE
Install addons error (gitlab-ci)

### ISSUE THREAD

**Issue by njeudy** [Tecnativa/doodba-qa#4]
Hello,

I try to use (and contribute) to doodba-qa and I have this error (think it's due to last commit for addons ..)

```
Traceback (most recent call last):
  File "/usr/local/bin/addons", line 59, in <module>
    for addon, repo in addons_config(strict=args.explicit):
  File "/usr/local/lib/python3.5/dist-packages/odoobaselib/__init__.py", line 91, in addons_config
    addon)
Exception: ('Addon without manifest', '/opt/odoo/custom/src/edi/LICENSE')
```

Some OCA repo have LICENSE file and I use "*" in addons.yml ..

- addons.yml

```
edi:
  - "*"
```

- repos.yml

```
./edi:
  defaults:
      depth: $DEPTH_DEFAULT
  remotes:
      origin: https://github.com/OCA/edi.git
      nj: https://github.com/njeudy/edi.git
  target:
      nj 11.0-waiting-pr
  merges:
      - nj 11.0-waiting-pr
```

If I had only module I want, it is working, .. but some repo have lots of modules :)
Did you encounter the same experience @Yajo ?

**Comment by yajo** [comment]
Not, because we personally never use the `*` feature.

It seems pretty obvious that there's a failure [in this method that expands the wildcards](https://github.com/Tecnativa/docker-odoo-base/blob/980a07aa64e3e6060137286caf8d5d00f4c8928a/lib/odoobaselib/__init__.py#L78-L99). I guess it should skip non-folder matches.

However one thing is true: it's expanding correctly. Maybe if you just use `*/` instead, it would skip non-dir automatically.

I'm closing this issue because this bug is not from doodba-qa itself, feel free to submit the patch to docker-odoo-base instead if you wish. Thanks!
